### ISSUE TITLE
No fragments found

### ISSUE THREAD

**Issue by nearspace-interface** [WhiteBlackGoose/hgt2png#1]
Hello,

I'm trying to use the tool but every time I run it it shows an error:

```
dotnet run hgt2png.csproj "/NASA SRTM 1 arc second V003"
Starting processing...
Looking for files in /NASA SRTM 1 arc second V003
No fragments found
```

Inside the folder I have 4 .hgt files named N04W074.hgt, N04W075.hgt, N05W074.hgt and N05W075.hgt. They are SRTMGL1 v003 files from the NASA. There is one of them attatched. Any idea what could cause it?
[N04W074.zip](https://github.com/WhiteBlackGoose/hgt2png/files/6347338/N04W074.zip)

**Comment by WhiteBlackGoose** [comment]
Maybe it should be "./NASA SRTM 1 arc second V003"? Otherwise it will look for them in the root. Just to test it, you can try providing the full (absolute) path to your directory

Edit: Hmmm, it indeed didn't find fragments. Let me see what can cause it

**Comment by WhiteBlackGoose** [comment]
@nearspace-interface that was my bad. It didn't work for such latitudes. Now I hope I fixed it, please, see if it works for you

**Comment by nearspace-interface** [comment]
Yes, it founds the files but now it throws this error:

```
Starting processing...
Looking for files in dems/
Found N04W074.hgt
Found N04W075.hgt
Found N05W074.hgt
Found N05W075.hgt
Interpolated dots in total: 0
Auto max byte: 16
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, IntPtr scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at hgt2png.Program.Main(String[] args) in /media/pierre/Archivos1/workworkwork/Near Space/Misiones/CO2/terrain/hgt2png/c#/hgt2png/hgt2png/Program.cs:line 173
```

Do I have to install other libraries?

**Comment by nearspace-interface** [comment]
I installed the lib with `sudo apt-get install libgdiplus` but now it says:

```
Starting processing...
Looking for files in dems/
Found N04W074.hgt
Found N04W075.hgt
Found N05W074.hgt
Found N05W075.hgt
Interpolated dots in total: 0
Auto max byte: 16
Unhandled exception. System.NotImplementedException: Not implemented.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at hgt2png.Program.Main(String[] args) in /media/pierre/Archivos1/workworkwork/Near Space/Misiones/CO2/terrain/hgt2png/c#/hgt2png/hgt2png/Program.cs:line 174
```
Any idea?

**Comment by WhiteBlackGoose** [comment]
@nearspace-interface  Alright... it gets more fun. I didn't test it on Linux, so it might take some time to fix it. If you want, you can help fixing it.

**Comment by nearspace-interface** [comment]
Well... I'll try. I don't have any experience with C# haha. Thank you very much anyway. I'll comment any news.

**Comment by WhiteBlackGoose** [comment]
Might make sense to move to ImageSharp or some other advanced image library.
